/**************************************************************************/
/*  midi_stream.cpp                                                       */
/**************************************************************************/
/*                         This file is part of:                          */
/*                            GOBLIN ENGINE                               */
/**************************************************************************/

#include "midi_stream.h"

#include "core/object/class_db.h"

#include "midi_stream_playback.h"
#include "thirdparty/tinysoundfont/tml.h"

void MidiStream::_bind_methods() {
	ClassDB::bind_method(D_METHOD("set_soundfont", "resource"), &MidiStream::set_soundfont);
	ClassDB::bind_method(D_METHOD("get_soundfont"), &MidiStream::get_soundfont);
	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "soundfont", PROPERTY_HINT_RESOURCE_TYPE, "SoundFontResource"), "set_soundfont", "get_soundfont");

	ClassDB::bind_method(D_METHOD("set_midi", "resource"), &MidiStream::set_midi);
	ClassDB::bind_method(D_METHOD("get_midi"), &MidiStream::get_midi);
	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "midi", PROPERTY_HINT_RESOURCE_TYPE, "MidiFileResource"), "set_midi", "get_midi");

	ClassDB::bind_method(D_METHOD("set_loop", "loop"), &MidiStream::set_loop);
	ClassDB::bind_method(D_METHOD("get_loop"), &MidiStream::get_loop);
	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "loop"), "set_loop", "get_loop");

	ClassDB::bind_method(D_METHOD("set_midi_speed", "speed"), &MidiStream::set_midi_speed);
	ClassDB::bind_method(D_METHOD("get_midi_speed"), &MidiStream::get_midi_speed);
	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "midi_speed", PROPERTY_HINT_RANGE, "0.1,4.0,0.01"), "set_midi_speed", "get_midi_speed");

	BIND_ENUM_CONSTANT(GM_ACOUSTIC_GRAND_PIANO);
	BIND_ENUM_CONSTANT(GM_BRIGHT_PIANO);
	BIND_ENUM_CONSTANT(GM_ELECTRIC_GRAND_PIANO);
	BIND_ENUM_CONSTANT(GM_HONKY_TONK_PIANO);
	BIND_ENUM_CONSTANT(GM_ELECTRIC_PIANO_1);
	BIND_ENUM_CONSTANT(GM_ELECTRIC_PIANO_2);
	BIND_ENUM_CONSTANT(GM_HARPSICHORD);
	BIND_ENUM_CONSTANT(GM_CLAV);
	BIND_ENUM_CONSTANT(GM_CELESTA);
	BIND_ENUM_CONSTANT(GM_GLOCKENSPIEL);
	BIND_ENUM_CONSTANT(GM_MUSIC_BOX);
	BIND_ENUM_CONSTANT(GM_VIBRAPHONE);
	BIND_ENUM_CONSTANT(GM_MARIMBA);
	BIND_ENUM_CONSTANT(GM_XYLOPHONE);
	BIND_ENUM_CONSTANT(GM_TUBULAR_BELLS);
	BIND_ENUM_CONSTANT(GM_DULCIMER);
	BIND_ENUM_CONSTANT(GM_DRAWBAR_ORGAN);
	BIND_ENUM_CONSTANT(GM_PERCUSSIVE_ORGAN);
	BIND_ENUM_CONSTANT(GM_ROCK_ORGAN);
	BIND_ENUM_CONSTANT(GM_CHURCH_ORGAN);
	BIND_ENUM_CONSTANT(GM_REED_ORGAN);
	BIND_ENUM_CONSTANT(GM_ACCORDION);
	BIND_ENUM_CONSTANT(GM_HARMONICA);
	BIND_ENUM_CONSTANT(GM_TANGO_ACCORDION);
	BIND_ENUM_CONSTANT(GM_NYLON_STRING_GUITAR);
	BIND_ENUM_CONSTANT(GM_STEEL_STRING_GUITAR);
	BIND_ENUM_CONSTANT(GM_JAZZ_GUITAR);
	BIND_ENUM_CONSTANT(GM_CLEAN_ELECTRIC_GUITAR);
	BIND_ENUM_CONSTANT(GM_MUTED_ELECTRIC_GUITAR);
	BIND_ENUM_CONSTANT(GM_OVERDRIVE_GUITAR);
	BIND_ENUM_CONSTANT(GM_DISTORTION_GUITAR);
	BIND_ENUM_CONSTANT(GM_GUITAR_HARMONICS);
	BIND_ENUM_CONSTANT(GM_ACOUSTIC_BASS);
	BIND_ENUM_CONSTANT(GM_FINGERED_BASS);
	BIND_ENUM_CONSTANT(GM_PICKED_BASS);
	BIND_ENUM_CONSTANT(GM_FRETLESS_BASS);
	BIND_ENUM_CONSTANT(GM_SLAP_BASS_1);
	BIND_ENUM_CONSTANT(GM_SLAP_BASS_2);
	BIND_ENUM_CONSTANT(GM_SYNTH_BASS_1);
	BIND_ENUM_CONSTANT(GM_SYNTH_BASS_2);
	BIND_ENUM_CONSTANT(GM_VIOLIN);
	BIND_ENUM_CONSTANT(GM_VIOLA);
	BIND_ENUM_CONSTANT(GM_CELLO);
	BIND_ENUM_CONSTANT(GM_CONTRABASS);
	BIND_ENUM_CONSTANT(GM_TREMOLO_STRINGS);
	BIND_ENUM_CONSTANT(GM_PIZZICATO_STRINGS);
	BIND_ENUM_CONSTANT(GM_ORCHESTRAL_HARP);
	BIND_ENUM_CONSTANT(GM_TIMPANI);
	BIND_ENUM_CONSTANT(GM_STRING_ENSEMBLE_1);
	BIND_ENUM_CONSTANT(GM_STRING_ENSEMBLE_2);
	BIND_ENUM_CONSTANT(GM_SYNTH_STRINGS_1);
	BIND_ENUM_CONSTANT(GM_SYNTH_STRINGS_2);
	BIND_ENUM_CONSTANT(GM_CHOIR_AAHS);
	BIND_ENUM_CONSTANT(GM_CHOIR_OOHS);
	BIND_ENUM_CONSTANT(GM_SYNTH_VOICE);
	BIND_ENUM_CONSTANT(GM_ORCHESTRAL_HIT);
	BIND_ENUM_CONSTANT(GM_TRUMPET);
	BIND_ENUM_CONSTANT(GM_TROMBONE);
	BIND_ENUM_CONSTANT(GM_TUBA);
	BIND_ENUM_CONSTANT(GM_MUTED_TRUMPET);
	BIND_ENUM_CONSTANT(GM_FRENCH_HORN);
	BIND_ENUM_CONSTANT(GM_BRASS_SECTION);
	BIND_ENUM_CONSTANT(GM_SYNTH_BRASS_1);
	BIND_ENUM_CONSTANT(GM_SYNTH_BRASS_2);
	BIND_ENUM_CONSTANT(GM_SOPRANO_SAX);
	BIND_ENUM_CONSTANT(GM_ALTO_SAX);
	BIND_ENUM_CONSTANT(GM_TENOR_SAX);
	BIND_ENUM_CONSTANT(GM_BARITONE_SAX);
	BIND_ENUM_CONSTANT(GM_OBOE);
	BIND_ENUM_CONSTANT(GM_ENGLISH_HORN);
	BIND_ENUM_CONSTANT(GM_BASSOON);
	BIND_ENUM_CONSTANT(GM_CLARINET);
	BIND_ENUM_CONSTANT(GM_PICCOLO);
	BIND_ENUM_CONSTANT(GM_FLUTE);
	BIND_ENUM_CONSTANT(GM_RECORDER);
	BIND_ENUM_CONSTANT(GM_PAN_FLUTE);
	BIND_ENUM_CONSTANT(GM_BLOWN_BOTTLE);
	BIND_ENUM_CONSTANT(GM_SHAKUHACHI);
	BIND_ENUM_CONSTANT(GM_WHISTLE);
	BIND_ENUM_CONSTANT(GM_OCARINA);
	BIND_ENUM_CONSTANT(GM_SQUARE_WAVE);
	BIND_ENUM_CONSTANT(GM_SAWTOOTH_WAVE);
	BIND_ENUM_CONSTANT(GM_CALLIOPE);
	BIND_ENUM_CONSTANT(GM_CHIFF);
	BIND_ENUM_CONSTANT(GM_CHARANG);
	BIND_ENUM_CONSTANT(GM_VOICE);
	BIND_ENUM_CONSTANT(GM_FIFTHS);
	BIND_ENUM_CONSTANT(GM_BASS_AND_LEAD);
	BIND_ENUM_CONSTANT(GM_NEW_AGE);
	BIND_ENUM_CONSTANT(GM_WARM);
	BIND_ENUM_CONSTANT(GM_POLYSYNTH);
	BIND_ENUM_CONSTANT(GM_CHOIR);
	BIND_ENUM_CONSTANT(GM_BOWED);
	BIND_ENUM_CONSTANT(GM_METALLIC);
	BIND_ENUM_CONSTANT(GM_HALO);
	BIND_ENUM_CONSTANT(GM_SWEEP);
	BIND_ENUM_CONSTANT(GM_FX_RAIN);
	BIND_ENUM_CONSTANT(GM_FX_SOUNDTRACK);
	BIND_ENUM_CONSTANT(GM_FX_CRYSTAL);
	BIND_ENUM_CONSTANT(GM_FX_ATMOSPHERE);
	BIND_ENUM_CONSTANT(GM_FX_BRIGHTNESS);
	BIND_ENUM_CONSTANT(GM_FX_GOBLINS);
	BIND_ENUM_CONSTANT(GM_FX_ECHO_DROPS);
	BIND_ENUM_CONSTANT(GM_FX_STAR_THEME);
	BIND_ENUM_CONSTANT(GM_SITAR);
	BIND_ENUM_CONSTANT(GM_BANJO);
	BIND_ENUM_CONSTANT(GM_SHAMISEN);
	BIND_ENUM_CONSTANT(GM_KOTO);
	BIND_ENUM_CONSTANT(GM_KALIMBA);
	BIND_ENUM_CONSTANT(GM_BAGPIPE);
	BIND_ENUM_CONSTANT(GM_FIDDLE);
	BIND_ENUM_CONSTANT(GM_SHANAI);
	BIND_ENUM_CONSTANT(GM_TINKLE_BELL);
	BIND_ENUM_CONSTANT(GM_AGOGO);
	BIND_ENUM_CONSTANT(GM_STEEL_DRUMS);
	BIND_ENUM_CONSTANT(GM_WOODBLOCK);
	BIND_ENUM_CONSTANT(GM_TAIKO_DRUM);
	BIND_ENUM_CONSTANT(GM_MELODIC_TOM);
	BIND_ENUM_CONSTANT(GM_SYNTH_DRUM);
	BIND_ENUM_CONSTANT(GM_REVERSE_CYMBAL);
	BIND_ENUM_CONSTANT(GM_GUITAR_FRET_NOISE);
	BIND_ENUM_CONSTANT(GM_BREATH_NOISE);
	BIND_ENUM_CONSTANT(GM_SEASHORE);
	BIND_ENUM_CONSTANT(GM_BIRD_TWEET);
	BIND_ENUM_CONSTANT(GM_TELEPHONE_RING);
	BIND_ENUM_CONSTANT(GM_HELICOPTER);
	BIND_ENUM_CONSTANT(GM_APPLAUSE);
	BIND_ENUM_CONSTANT(GM_GUNSHOT);

	BIND_ENUM_CONSTANT(NOTE_C0);
	BIND_ENUM_CONSTANT(NOTE_CS0);
	BIND_ENUM_CONSTANT(NOTE_D0);
	BIND_ENUM_CONSTANT(NOTE_DS0);
	BIND_ENUM_CONSTANT(NOTE_E0);
	BIND_ENUM_CONSTANT(NOTE_F0);
	BIND_ENUM_CONSTANT(NOTE_FS0);
	BIND_ENUM_CONSTANT(NOTE_G0);
	BIND_ENUM_CONSTANT(NOTE_GS0);
	BIND_ENUM_CONSTANT(NOTE_A0);
	BIND_ENUM_CONSTANT(NOTE_AS0);
	BIND_ENUM_CONSTANT(NOTE_B0);
	BIND_ENUM_CONSTANT(NOTE_C1);
	BIND_ENUM_CONSTANT(NOTE_CS1);
	BIND_ENUM_CONSTANT(NOTE_D1);
	BIND_ENUM_CONSTANT(NOTE_DS1);
	BIND_ENUM_CONSTANT(NOTE_E1);
	BIND_ENUM_CONSTANT(NOTE_F1);
	BIND_ENUM_CONSTANT(NOTE_FS1);
	BIND_ENUM_CONSTANT(NOTE_G1);
	BIND_ENUM_CONSTANT(NOTE_GS1);
	BIND_ENUM_CONSTANT(NOTE_A1);
	BIND_ENUM_CONSTANT(NOTE_AS1);
	BIND_ENUM_CONSTANT(NOTE_B1);
	BIND_ENUM_CONSTANT(NOTE_C2);
	BIND_ENUM_CONSTANT(NOTE_CS2);
	BIND_ENUM_CONSTANT(NOTE_D2);
	BIND_ENUM_CONSTANT(NOTE_DS2);
	BIND_ENUM_CONSTANT(NOTE_E2);
	BIND_ENUM_CONSTANT(NOTE_F2);
	BIND_ENUM_CONSTANT(NOTE_FS2);
	BIND_ENUM_CONSTANT(NOTE_G2);
	BIND_ENUM_CONSTANT(NOTE_GS2);
	BIND_ENUM_CONSTANT(NOTE_A2);
	BIND_ENUM_CONSTANT(NOTE_AS2);
	BIND_ENUM_CONSTANT(NOTE_B2);
	BIND_ENUM_CONSTANT(NOTE_C3);
	BIND_ENUM_CONSTANT(NOTE_CS3);
	BIND_ENUM_CONSTANT(NOTE_D3);
	BIND_ENUM_CONSTANT(NOTE_DS3);
	BIND_ENUM_CONSTANT(NOTE_E3);
	BIND_ENUM_CONSTANT(NOTE_F3);
	BIND_ENUM_CONSTANT(NOTE_FS3);
	BIND_ENUM_CONSTANT(NOTE_G3);
	BIND_ENUM_CONSTANT(NOTE_GS3);
	BIND_ENUM_CONSTANT(NOTE_A3);
	BIND_ENUM_CONSTANT(NOTE_AS3);
	BIND_ENUM_CONSTANT(NOTE_B3);
	BIND_ENUM_CONSTANT(NOTE_C4);
	BIND_ENUM_CONSTANT(NOTE_CS4);
	BIND_ENUM_CONSTANT(NOTE_D4);
	BIND_ENUM_CONSTANT(NOTE_DS4);
	BIND_ENUM_CONSTANT(NOTE_E4);
	BIND_ENUM_CONSTANT(NOTE_F4);
	BIND_ENUM_CONSTANT(NOTE_FS4);
	BIND_ENUM_CONSTANT(NOTE_G4);
	BIND_ENUM_CONSTANT(NOTE_GS4);
	BIND_ENUM_CONSTANT(NOTE_A4);
	BIND_ENUM_CONSTANT(NOTE_AS4);
	BIND_ENUM_CONSTANT(NOTE_B4);
	BIND_ENUM_CONSTANT(NOTE_C5);
	BIND_ENUM_CONSTANT(NOTE_CS5);
	BIND_ENUM_CONSTANT(NOTE_D5);
	BIND_ENUM_CONSTANT(NOTE_DS5);
	BIND_ENUM_CONSTANT(NOTE_E5);
	BIND_ENUM_CONSTANT(NOTE_F5);
	BIND_ENUM_CONSTANT(NOTE_FS5);
	BIND_ENUM_CONSTANT(NOTE_G5);
	BIND_ENUM_CONSTANT(NOTE_GS5);
	BIND_ENUM_CONSTANT(NOTE_A5);
	BIND_ENUM_CONSTANT(NOTE_AS5);
	BIND_ENUM_CONSTANT(NOTE_B5);
	BIND_ENUM_CONSTANT(NOTE_C6);
	BIND_ENUM_CONSTANT(NOTE_CS6);
	BIND_ENUM_CONSTANT(NOTE_D6);
	BIND_ENUM_CONSTANT(NOTE_DS6);
	BIND_ENUM_CONSTANT(NOTE_E6);
	BIND_ENUM_CONSTANT(NOTE_F6);
	BIND_ENUM_CONSTANT(NOTE_FS6);
	BIND_ENUM_CONSTANT(NOTE_G6);
	BIND_ENUM_CONSTANT(NOTE_GS6);
	BIND_ENUM_CONSTANT(NOTE_A6);
	BIND_ENUM_CONSTANT(NOTE_AS6);
	BIND_ENUM_CONSTANT(NOTE_B6);
	BIND_ENUM_CONSTANT(NOTE_C7);
	BIND_ENUM_CONSTANT(NOTE_CS7);
	BIND_ENUM_CONSTANT(NOTE_D7);
	BIND_ENUM_CONSTANT(NOTE_DS7);
	BIND_ENUM_CONSTANT(NOTE_E7);
	BIND_ENUM_CONSTANT(NOTE_F7);
	BIND_ENUM_CONSTANT(NOTE_FS7);
	BIND_ENUM_CONSTANT(NOTE_G7);
	BIND_ENUM_CONSTANT(NOTE_GS7);
	BIND_ENUM_CONSTANT(NOTE_A7);
	BIND_ENUM_CONSTANT(NOTE_AS7);
	BIND_ENUM_CONSTANT(NOTE_B7);
	BIND_ENUM_CONSTANT(NOTE_C8);
	BIND_ENUM_CONSTANT(NOTE_CS8);
	BIND_ENUM_CONSTANT(NOTE_D8);
	BIND_ENUM_CONSTANT(NOTE_DS8);
	BIND_ENUM_CONSTANT(NOTE_E8);
	BIND_ENUM_CONSTANT(NOTE_F8);
	BIND_ENUM_CONSTANT(NOTE_FS8);
	BIND_ENUM_CONSTANT(NOTE_G8);
	BIND_ENUM_CONSTANT(NOTE_GS8);
	BIND_ENUM_CONSTANT(NOTE_A8);
	BIND_ENUM_CONSTANT(NOTE_AS8);
	BIND_ENUM_CONSTANT(NOTE_B8);
	BIND_ENUM_CONSTANT(NOTE_C9);
	BIND_ENUM_CONSTANT(NOTE_CS9);
	BIND_ENUM_CONSTANT(NOTE_D9);
	BIND_ENUM_CONSTANT(NOTE_DS9);
	BIND_ENUM_CONSTANT(NOTE_E9);
	BIND_ENUM_CONSTANT(NOTE_F9);
	BIND_ENUM_CONSTANT(NOTE_FS9);
	BIND_ENUM_CONSTANT(NOTE_G9);
	BIND_ENUM_CONSTANT(NOTE_GS9);
	BIND_ENUM_CONSTANT(NOTE_A9);
	BIND_ENUM_CONSTANT(NOTE_AS9);
	BIND_ENUM_CONSTANT(NOTE_B9);
	BIND_ENUM_CONSTANT(NOTE_C10);
	BIND_ENUM_CONSTANT(NOTE_CS10);
	BIND_ENUM_CONSTANT(NOTE_D10);
	BIND_ENUM_CONSTANT(NOTE_DS10);
	BIND_ENUM_CONSTANT(NOTE_E10);
	BIND_ENUM_CONSTANT(NOTE_F10);
	BIND_ENUM_CONSTANT(NOTE_FS10);
	BIND_ENUM_CONSTANT(NOTE_G10);

	BIND_ENUM_CONSTANT(DRUM_ACOUSTIC_BASS_DRUM);
	BIND_ENUM_CONSTANT(DRUM_BASS_DRUM_1);
	BIND_ENUM_CONSTANT(DRUM_SIDE_STICK);
	BIND_ENUM_CONSTANT(DRUM_ACOUSTIC_SNARE);
	BIND_ENUM_CONSTANT(DRUM_HAND_CLAP);
	BIND_ENUM_CONSTANT(DRUM_ELECTRIC_SNARE);
	BIND_ENUM_CONSTANT(DRUM_LOW_FLOOR_TOM);
	BIND_ENUM_CONSTANT(DRUM_CLOSED_HI_HAT);
	BIND_ENUM_CONSTANT(DRUM_HIGH_FLOOR_TOM);
	BIND_ENUM_CONSTANT(DRUM_PEDAL_HI_HAT);
	BIND_ENUM_CONSTANT(DRUM_LOW_TOM);
	BIND_ENUM_CONSTANT(DRUM_OPEN_HI_HAT);
	BIND_ENUM_CONSTANT(DRUM_LOW_MID_TOM);
	BIND_ENUM_CONSTANT(DRUM_HI_MID_TOM);
	BIND_ENUM_CONSTANT(DRUM_CRASH_CYMBAL_1);
	BIND_ENUM_CONSTANT(DRUM_HIGH_TOM);
	BIND_ENUM_CONSTANT(DRUM_RIDE_CYMBAL_1);
	BIND_ENUM_CONSTANT(DRUM_CHINESE_CYMBAL);
	BIND_ENUM_CONSTANT(DRUM_RIDE_BELL);
	BIND_ENUM_CONSTANT(DRUM_TAMBOURINE);
	BIND_ENUM_CONSTANT(DRUM_SPLASH_CYMBAL);
	BIND_ENUM_CONSTANT(DRUM_COWBELL);
	BIND_ENUM_CONSTANT(DRUM_CRASH_CYMBAL_2);
	BIND_ENUM_CONSTANT(DRUM_VIBRASLAP);
	BIND_ENUM_CONSTANT(DRUM_RIDE_CYMBAL_2);
	BIND_ENUM_CONSTANT(DRUM_HI_BONGO);
	BIND_ENUM_CONSTANT(DRUM_LOW_BONGO);
	BIND_ENUM_CONSTANT(DRUM_MUTE_HI_CONGA);
	BIND_ENUM_CONSTANT(DRUM_OPEN_HI_CONGA);
	BIND_ENUM_CONSTANT(DRUM_LOW_CONGA);
	BIND_ENUM_CONSTANT(DRUM_HIGH_TIMBALE);
	BIND_ENUM_CONSTANT(DRUM_LOW_TIMBALE);
	BIND_ENUM_CONSTANT(DRUM_HIGH_AGOGO);
	BIND_ENUM_CONSTANT(DRUM_LOW_AGOGO);
	BIND_ENUM_CONSTANT(DRUM_CABASA);
	BIND_ENUM_CONSTANT(DRUM_MARACAS);
	BIND_ENUM_CONSTANT(DRUM_SHORT_WHISTLE);
	BIND_ENUM_CONSTANT(DRUM_LONG_WHISTLE);
	BIND_ENUM_CONSTANT(DRUM_SHORT_GUIRO);
	BIND_ENUM_CONSTANT(DRUM_LONG_GUIRO);
	BIND_ENUM_CONSTANT(DRUM_CLAVES);
	BIND_ENUM_CONSTANT(DRUM_HI_WOOD_BLOCK);
	BIND_ENUM_CONSTANT(DRUM_LOW_WOOD_BLOCK);
	BIND_ENUM_CONSTANT(DRUM_MUTE_CUICA);
	BIND_ENUM_CONSTANT(DRUM_OPEN_CUICA);
	BIND_ENUM_CONSTANT(DRUM_MUTE_TRIANGLE);
	BIND_ENUM_CONSTANT(DRUM_OPEN_TRIANGLE);
	BIND_ENUM_CONSTANT(DRUM_SHAKER);
}

void MidiStream::set_soundfont(const Ref<SoundFontResource> &p_resource) {
	soundfont_resource = p_resource;
}

Ref<SoundFontResource> MidiStream::get_soundfont() const {
	return soundfont_resource;
}

void MidiStream::set_midi(const Ref<MidiFileResource> &p_resource) {
	midi_resource = p_resource;
	midi_length_ms = 0;
	if (midi_resource.is_valid() && !midi_resource->get_data().is_empty()) {
		tml_message *tmp = tml_load_memory(midi_resource->get_data().ptr(), (int)midi_resource->get_data().size());
		if (tmp) {
			unsigned int first_note_ms = 0;
			unsigned int length_ms = 0;
			tml_get_info(tmp, nullptr, nullptr, nullptr, &first_note_ms, &length_ms);
			midi_length_ms = (uint32_t)length_ms;
			tml_free(tmp);
		}
	}
}

Ref<MidiFileResource> MidiStream::get_midi() const {
	return midi_resource;
}

void MidiStream::set_loop(bool p_loop) {
	loop = p_loop;
}

bool MidiStream::get_loop() const {
	return loop;
}

void MidiStream::set_midi_speed(float p_speed) {
	if (p_speed <= 0.0f) {
		p_speed = 1.0f;
	}
	midi_speed = p_speed;
}

float MidiStream::get_midi_speed() const {
	return midi_speed;
}

Ref<AudioStreamPlayback> MidiStream::instantiate_playback() {
	Ref<MidiStreamPlayback> pb;
	pb.instantiate();
	pb->set_stream(Ref<MidiStream>(this));
	return pb;
}

String MidiStream::get_stream_name() const {
	return "MIDI Stream";
}

double MidiStream::get_length() const {
	return (double)midi_length_ms / 1000.0;
}

bool MidiStream::is_monophonic() const {
	return false;
}

bool MidiStream::has_loop() const {
	return loop;
}
