#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env_goblin")

# MIDI / SoundFont module: MidiStream (AudioStream) + TinySoundFont synth +
# importers + tests. Additive sources, no upstream files touched.
env_goblin.add_source_files(env_goblin.goblin_sources, "*.cpp")
