#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_goblin")

env_goblin.add_source_files(env_goblin.goblin_sources, "*.cpp")

# Add Goblin icon path to editor icons (matches editor/icons/*.svg)
# The module_icons_paths will automatically include goblin icons in the generation
goblin_module_path = Dir("..").abspath
env.module_icons_paths.append(goblin_module_path + "/editor/icons")
