#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_goblin")

env_goblin.add_source_files(env_goblin.goblin_sources, "*.cpp")

# NOTE: editor icon overrides (Logo.svg, Godot.svg, TitleBarLogo.svg) are
# registered via config.get_icons_path() at configure time. Appending
# module_icons_paths from here would run after editor/icons/SCsub and the
# overrides would never apply.
