#!/usr/bin/env python
import os

Import('env')

env_goblin = env.Clone()
env_goblin.add_source_files(env.modules_sources, "*.cpp")
env_goblin.add_source_files(env.modules_sources, "io/*.cpp")

env_goblin.add_source_files(env.modules_sources, "libs/*.c")

env_goblin.disable_warnings()