#!/usr/bin/env python
import os

Import("env")

env_dascript = env.Clone()
env_dascript.add_source_files(env.modules_sources, "*.cpp")
env_dascript.add_source_files(env.modules_sources, "src/*.cpp")


env_dascript.disable_warnings()
