name: 🤖 Android Builds
on: [push, pull_request]

# Global Settings
env:
  GODOT_BASE_BRANCH: main
  SCONSFLAGS: verbose=yes warnings=all debug_symbols=no deprecated=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes)
            cache-name: android-editor
            target: release_debug
            tools: true
            sconsflags: module_sqlite_enabled=yes use_llvm=yes
            cmd: generateGodotEditor

          - name: Template (target=release, tools=no)
            cache-name: android-template
            target: release
            tools: false
            sconsflags:
            cmd: generateGodotTemplates

    steps:
      - uses: actions/checkout@v3

      # Azure repositories are not reliable, we need to prevent azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Goblin build cache
        uses: ./.github/actions/goblin-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/goblin-deps

      - name: Compilation (armv7)
        uses: ./.github/actions/goblin-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} android_arch=armv7
          platform: android
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}

      - name: Compilation (arm64v8)
        uses: ./.github/actions/goblin-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} android_arch=arm64v8
          platform: android
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }

      - name: Generate Godot templates
        run: |
          cd platform/android/java
          ./gradlew generateGodotTemplates
          cd ../../..
          ls -l bin/

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
