name: 🤖 Android Builds
on: [push, pull_request]

# Global Settings
env:
  GODOT_BASE_BRANCH: main
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no use_thinlto=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  android-template:
    runs-on: "ubuntu-20.04"

    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      # Azure repositories are not reliable, we need to prevent azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Goblin build cache
        uses: ./.github/actions/goblin-cache
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/goblin-deps

      - name: Compilation (armv7)
        uses: ./.github/actions/goblin-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} android_arch=armv7
          platform: android
          target: release
          tools: false

      - name: Compilation (arm64v8)
        uses: ./.github/actions/goblin-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} android_arch=arm64v8
          platform: android
          target: release
          tools: false

      - name: Generate Goblin templates
        run: |
          cd platform/android/java
          chmod +x gradlew
          ./gradlew generateGodotTemplates
          cd ../../..
          ls -l bin/

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
