name: 🌐 JavaScript Builds
on: [push, pull_request]

# Global Settings
env:
  GODOT_BASE_BRANCH: main
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no deprecated=no -j8
  EM_VERSION: 2.0.25
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-javascript
  cancel-in-progress: true

jobs:
  javascript-template:
    runs-on: "ubuntu-20.04"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      # Additional cache for Emscripten generated system libraries
      - name: Load Emscripten cache
        id: javascript-template-emscripten-cache
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{github.job}}

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Setup Goblin build cache
        uses: ./.github/actions/goblin-cache
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/goblin-deps

      - name: Compilation
        uses: ./.github/actions/goblin-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: javascript
          target: release
          tools: false

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
