name: 🌐 JavaScript Builds
on: [push, pull_request]

# Global Settings
env:
  GODOT_BASE_BRANCH: main
  SCONSFLAGS: verbose=yes warnings=all debug_symbols=no deprecated=no
  EM_VERSION: 3.1.18
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-javascript
  cancel-in-progress: true

jobs:
  build-javascript:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes)
            cache-name: javascript-editor
            target: release_debug
            tools: true
            sconsflags: module_sqlite_enabled=yes threads_enabled=yes x11=no

          - name: Template (target=release, tools=no, threads_enabled=no)
            cache-name: javascript-template
            target: release
            tools: false
            sconsflags: threads_enabled=no

    steps:
      - uses: actions/checkout@v3

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Setup Goblin build cache
        uses: ./.github/actions/goblin-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/goblin-deps

      - name: Compilation
        uses: ./.github/actions/goblin-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: javascript
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
