name: 🍎 macOS Builds
on: [push, pull_request]

# Global Settings
env:
  GODOT_BASE_BRANCH: main
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no use_thinlto=yes deprecated=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes)
            cache-name: macos-editor
            target: release_debug
            tools: true
            bin: "./bin/goblin.osx.opt.tools.64"
            sconsflags: module_sqlite_enabled=yes

          - name: Template (target=release, tools=no)
            cache-name: macos-template
            target: release
            tools: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup Goblin build cache
        uses: ./.github/actions/goblin-cache
        with:
          cache-name: ${{ matrix.cache-name }} ${{ matrix.sconsflags }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/goblin-deps

      - name: Compilation
        uses: ./.github/actions/goblin-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: osx
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
